### ISSUE TITLE
Key bindings does not work

### ISSUE THREAD

**Issue by akirayamamoto** [shagabutdinov/sublime-open-path#3]
F10 and Ctrl + F10 key bindings does not work for me. Launching the command from Command Pallet works. I am using Sublime Text 3 and Windows 7 64 bits.

Thanks.

**Comment by shagabutdinov** [comment]
You should set a "sublime_enhanced_keybindings" setting to true in order to activate default shortcuts of all plugins (described here: https://github.com/shagabutdinov/sublime-enhanced/blob/master/readme-warning.md).

Another way to activate shortcuts is to add it to your user keymap file: 

```
[
  {
    "keys": ["f10"],
    "command": "open_project_folder",
  },

  {
    "keys": ["ctrl+f10"],
    "command": "open_file_folder",
  }
]
```

**Comment by shagabutdinov** [comment]
If you still have this issue please reopen it and show your console output when pressing f10/ctrl+f10 buttons.

**Comment by akirayamamoto** [comment]
Thanks! It is working now.
